lista = [
    "comida", "viagem", "gabarito", "carro", "fumaça",
    "livro", "caderno", "computador", "celular", "mesa",
    "cadeira", "bicicleta", "aviao", "trem", "barco",
    "prato", "garfo", "faca", "colher", "panela",
    "televisão", "rádio", "música", "filme", "documentário",
    "internet", "programação", "escola", "faculdade", "universidade",
    "professor", "aluno", "diretor", "engenheiro", "médico",
    "hospital", "farmácia", "mercado", "padaria", "restaurante",
    "parque", "praça", "jardim", "floresta", "deserto",
    "praia", "montanha", "rio", "lago", "mar",
    "cachoeira", "piscina", "banheira", "chuveiro", "sabão",
    "shampoo", "condicionador", "toalha", "roupa", "sapato",
    "sandália", "chinelo", "meia", "calça", "camisa",
    "blusa", "casaco", "jaqueta", "chapéu", "boné",
    "óculos", "relógio", "pulseira", "anel", "brinco",
    "colher", "garrafa", "copo", "xícara", "caneca",
    "livro", "revista", "jornal", "notícia", "artigo",
    "tarefa", "projeto", "trabalho", "apresentação", "discurso",
    "palestra", "reunião", "evento", "festa", "celebração",
    "aniversário", "casamento", "boda", "batizado", "férias",
    "feriado", "fim de semana", "dia útil", "manhã", "tarde",
    "noite", "madrugada", "inverno", "primavera", "verão",
    "outono", "sol", "chuva", "nuvem", "tempestade"
]
